### ISSUE TITLE
Local result folder lookup fails

### ISSUE THREAD

**Issue by sorewachigauyo** [qiboteam/qibo-client#44]
On my machine, line https://github.com/qiboteam/qibo-client/blob/main/src/qibo_client/qibo_client.py#L224 fails

```
Traceback (most recent call last):
  File "c:\Users\pault\Documents\repos\qibo-client\test.py", line 12, in <module>
    results = client.run_circuit(circ, nshots=1000)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pault\Documents\repos\qibo-client\src\qibo_client\qibo_client.py", line 177, in run_circuit
    result = self._get_result()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\pault\Documents\repos\qibo-client\src\qibo_client\qibo_client.py", line 225, in _get_result
    self.results_folder = constants.RESULTS_BASE_FOLDER / self.pid
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'WindowsPath' and 'int'
```

I hacked it to work by casting `self.pid` to a string.

**Comment by sorewachigauyo** [comment]
Nevermind, I realize that on your provider, you return that parameter as a string.
